Repository frontend-park-mail-ru/2022_2_Base, pull requests merged in 2022-11, with the labels that each got.

#20 Base-2.10 webpack router
  .eslintignore
  .gitignore
  README.md
  babel.config.js
  package-lock.json
  package.json
  public/img/favicon.png
  public/img/favicon/android-chrome-192x192.png
  public/img/favicon/android-chrome-512x512.png
  public/img/favicon/favicon-16x16.png
  public/img/favicon/favicon-32x32.png
  public/img/favicon/site.webmanifest
  public/index.hbs
  public/index.html
  public/index.scss
  public/src/components/BaseComponent.js
  public/src/components/Footer/Footer.js
  public/src/components/Footer/footer.hbs
  public/src/components/Footer/footer.scss
  public/src/components/Form/Form.js
  public/src/components/Form/form.hbs
  public/src/components/Form/form.scss
  public/src/components/Header/Header.js
  public/src/components/Header/header.hbs
  public/src/components/Header/header.scss
  public/src/components/ItemCard/ItemCard.js
  public/src/components/ItemCard/itemCard.hbs
  public/src/components/ItemCard/itemCard.scss
  public/src/components/TopCategory/TopCategory.js
  public/src/components/TopCategory/topCategory.hbs
  public/src/components/TopCategory/topCategory.scss
  public/src/index.js
  public/src/modules/Router.js
  public/src/modules/ajax.js
  public/src/pages/ErrorPage/ErrorPage.js
  public/src/pages/ErrorPage/errorPage.hbs
  public/src/pages/LoginPage/LoginPage.css
  public/src/pages/LoginPage/LoginPage.hbs
  public/src/pages/LoginPage/LoginPage.js
  public/src/pages/LoginPage/LoginPage.scss
  public/src/pages/MainPage/MainPage.hbs
  public/src/pages/MainPage/MainPage.js
  public/src/pages/MainPage/MainPage.scss
  public/src/pages/RegisterPage/RegisterPage.css
  public/src/pages/RegisterPage/RegisterPage.hbs
  public/src/pages/RegisterPage/RegisterPage.js
  public/src/pages/RegisterPage/RegisterPage.scss
  server/index.js
  webpack.config.js
Labels: Ждет ревью команды

#23 Base 2.9 base view & store
  .github/workflows/ci.yml
  public/src/components/BaseComponent.js
  public/src/stores/BaseStore.js
  public/src/views/BaseView.js
Labels: ОК

#29 search + merge fix
  public/src/actions/itemCards.js
  public/src/components/CartItem/CartItem.hbs
  public/src/components/CatalogItemCard/CatalogItemCard.hbs
  public/src/components/Footer/footer.scss
  public/src/components/Header/Header.js
  public/src/components/Header/header.hbs
  public/src/components/Header/header.scss
  public/src/components/InfoCard/AddressCard/AddressCard.js
  public/src/components/InfoCard/AddressCard/AddressCard.scss
  public/src/components/InfoCard/BaseInfoCard.js
  public/src/components/InfoCard/PaymentCard/PaymentCard.js
  public/src/components/ItemCard/itemCard.hbs
  public/src/components/PopUpChooseAddressAndPaymentCard/PopUpChooseAddressAndPaymentCard.js
  public/src/components/SearchSuggestion/SearchSuggestion.hbs
  public/src/components/SearchSuggestion/SearchSuggestion.js
  public/src/components/SearchSuggestion/SearchSuggestion.scss
  public/src/config.js
  public/src/index.js
  public/src/modules/ErrorMessage.js
  public/src/modules/Router.js
  public/src/modules/refreshElements.js
  public/src/modules/validation.js
  public/src/pages/CartPage/CartPage.hbs
  public/src/pages/CartPage/CartPage.js
  public/src/pages/CartPage/CartPage.scss
  public/src/pages/CatalogPage/CatalogPage.hbs
  public/src/pages/CatalogPage/CatalogPage.js
  public/src/pages/CatalogPage/CatalogPage.scss
  public/src/pages/CatalogPage/CategoryPage/CategoryPage.js
  public/src/pages/CatalogPage/SearchPage/SearchPage.js
  public/src/pages/ErrorPage/ErrorPage.js
  public/src/pages/UserPage/UserPage.hbs
  public/src/pages/UserPage/UserPage.scss
  public/src/stores/CartStore.js
  public/src/stores/ItemsStore.js
Labels: ОК

#28 product + review page
  public/img/Comment.svg
  public/img/ReturnArrow.png
  public/img/dislike-finger.svg
  public/img/like-finger.svg
  public/index.scss
  public/src/actions/itemCards.js
  public/src/components/AddToCartButton/AddToCartButton.hbs
  public/src/components/AddToCartButton/AddToCartButton.js
  public/src/components/AddToCartButton/AddToCartButton.scss
  public/src/components/CartItem/CartItem.hbs
  public/src/components/CatalogItemCard/CatalogItemCard.hbs
  public/src/components/Comment/Comment.hbs
  public/src/components/Comment/Comment.js
  public/src/components/Comment/Comment.scss
  public/src/components/Footer/footer.scss
  public/src/components/Header/Header.js
  public/src/components/Header/header.scss
  public/src/components/InfoCard/AddressCard/AddressCard.scss
  public/src/components/InfoCard/AddressCard/addressCard.hbs
  public/src/components/InfoCard/BaseInfoCard.js
  public/src/components/InfoCard/PaymentCard/PaymentCard.scss
  public/src/components/InfoCard/PaymentCard/paymentCard.hbs
  public/src/components/ItemCard/itemCard.hbs
  public/src/components/ItemCard/itemCard.scss
  public/src/components/PopUpChooseAddressAndPaymentCard/PopUpChooseAddressAndPaymentCard.hbs
  public/src/components/ProductHeader/ProductHeader.hbs
  public/src/components/ProductHeader/ProductHeader.js
  public/src/components/ProductHeader/ProductHeader.scss
  public/src/components/popUp/PopUpEditUserInfo/PopUpEditUserInfo.js
  public/src/config.js
  public/src/index.js
  public/src/modules/Router.js
  public/src/modules/refreshElements.js
  public/src/modules/sharedFunctions.js
  public/src/modules/validation.js
  public/src/pages/CartPage/CartPage.hbs
  public/src/pages/CartPage/CartPage.js
  public/src/pages/CartPage/CartPage.scss
  public/src/pages/CatalogPage/CatalogPage.hbs
  public/src/pages/CatalogPage/CatalogPage.js
  public/src/pages/CatalogPage/CatalogPage.scss
  public/src/pages/CatalogPage/CategoryPage/CategoryPage.js
  public/src/pages/CatalogPage/SearchPage/SearchPage.js
  public/src/pages/ItemPage/AddCommentPage/AddCommentPage.hbs
  public/src/pages/ItemPage/AddCommentPage/AddCommentPage.js
  public/src/pages/ItemPage/AddCommentPage/AddCommentPage.scss
  public/src/pages/ItemPage/BaseItemPage.js
  public/src/pages/ItemPage/CommentPage/CommentPage.hbs
  public/src/pages/ItemPage/CommentPage/CommentPage.js
  public/src/pages/ItemPage/CommentPage/CommentPage.scss
  public/src/pages/ItemPage/ProductPage/ProductPage.hbs
  public/src/pages/ItemPage/ProductPage/ProductPage.js
  public/src/pages/ItemPage/ProductPage/ProductPage.scss
  public/src/pages/LoginPage/LoginPage.js
  public/src/pages/RegisterPage/RegisterPage.js
  public/src/pages/UserPage/UserPage.hbs
  public/src/stores/CartStore.js
  public/src/stores/ItemsStore.js
  public/src/stores/UserStore.js
Labels: ОК

#30 orders page
  public/index.scss
  public/src/actions/order.js
  public/src/components/BaseComponent.js
  public/src/components/CartItem/CartItem.hbs
  public/src/components/CatalogItemCard/CatalogItemCard.hbs
  public/src/components/Header/Header.js
  public/src/components/Header/header.hbs
  public/src/components/Header/header.scss
  public/src/components/InfoCard/PaymentCard/paymentCard.hbs
  public/src/components/ItemCard/itemCard.hbs
  public/src/components/OrderBlock/OrderBlock.hbs
  public/src/components/OrderBlock/OrderBlock.js
  public/src/components/OrderBlock/OrderBlock.scss
  public/src/components/ProductHeader/ProductHeader.hbs
  public/src/components/ProductHeader/ProductHeader.scss
  public/src/components/SearchSuggestion/SearchSuggestion.hbs
  public/src/components/SearchSuggestion/SearchSuggestion.scss
  public/src/config.js
  public/src/index.js
  public/src/modules/Router.js
  public/src/modules/sharedFunctions.js
  public/src/modules/validation.js
  public/src/pages/CartPage/CartPage.hbs
  public/src/pages/CatalogPage/CatalogPage.hbs
  public/src/pages/CatalogPage/CatalogPage.js
  public/src/pages/ItemPage/AddCommentPage/AddCommentPage.hbs
  public/src/pages/ItemPage/CommentPage/CommentPage.hbs
  public/src/pages/ItemPage/CommentPage/CommentPage.js
  public/src/pages/ItemPage/ProductPage/ProductPage.hbs
  public/src/pages/ItemPage/ProductPage/ProductPage.scss
  public/src/pages/OrdersPage/OrdersPage.hbs
  public/src/pages/OrdersPage/OrdersPage.js
  public/src/pages/OrdersPage/OrdersPage.scss
  public/src/pages/UserPage/UserPage.hbs
  public/src/pages/UserPage/UserPage.js
  public/src/stores/ItemsStore.js
  public/src/stores/OrdersStore.js
  public/src/stores/UserStore.js
  server/index.js
Labels: Нужны исправления
